### ISSUE TITLE
iRacing Telemetry Data

### ISSUE THREAD

**Issue by arilink-tech** [SlicedSilver/iRduino#60]
Hello, I found your code for obtaining iRacing telemetry data on Github. I want to DIY a dashboard and need to obtain iRacing telemetry data, but I don’t have a parsing document for iRacing shared memory. Could you please give me? Looking forward to your help

**Comment by SlicedSilver** [comment]
I haven't been a member on iRacing for a long time but I'm positive that the best place to look for help would be on the iRacing forums. Try to find a sub-forum regarding 'SDK' and start from there. There will most likely be a SDK wrapper in the programming language you are looking for.

**Comment by arilink-tech** [comment]
Ok
Thank you very much
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SlicedSilver/iRduino"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上11:08
收件人:&nbsp;"SlicedSilver/iRduino"<iRduino@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SlicedSilver/iRduino] iRacing Telemetry Data (#60)





 
I haven't been a member on iRacing for a long time but I'm positive that the best place to look for help would be on the iRacing forums. Try to find a sub-forum regarding 'SDK' and start from there. There will most likely be a SDK wrapper in the programming language you are looking for.
